### ISSUE TITLE
Invalid GUI text on X11 Tunnel

### ISSUE THREAD

**Issue by void-in** [infobyte/faraday#21] opened 2014-12-17 05:59 UTC
The GUI text appear all gibberish when Farady (Community version) is launched on SSH session where X11 is tunneled. 
![farady-gui](https://cloud.githubusercontent.com/assets/1746697/5467112/6d709a7c-85db-11e4-99f0-4eb38f788899.JPG)

Works fine when launched on the native terminal.

**Comment by f-amato** [comment] 2015-04-13 20:54
Did you try the same platform to run another tools? We didn't know the Xming maybe it's a problem with this.

**Comment by void-in** [comment] 2015-04-14 05:09
@f-amato I can test other GUIs such as firefox and zenmap just find. 
![xming_zenmap_gui](https://cloud.githubusercontent.com/assets/1746697/7130662/c305627e-e28d-11e4-8b61-084c9bf2aadc.JPG)
The reason I mentioned this as a bug is that Farady use thick client for GUI and since most of the offensive tools are Linux based, a lot of times these boxes won't be interacted through GUIs. More than 90% of the time I only use SSH for performing penetration testing through Kali. Although Xming isn't the only solution for X11 forwarding on Windows, it is one of the most widely used. And since it is able to draw all other GUIs I have tested without any problem, I think it is a problem with Farady. Since I got a response after more than three months and the issue is immediately closed, so I think I don't need to investigate this any further.

**Comment by f-amato** [comment] 2015-04-14 13:58
Sorry the delay, I can't close the issue. We are planning to migrate QT3 I'm pretty sure that it's a problem with compatibility.
I just tried with a few linux distribution X11 forwarding and we can't reproduce the bug.
Could you please try the latest version of Faraday with another Linux to be sure that it's something with QT3 + Xming ?

**Comment by void-in** [comment] 2015-04-14 14:13
@f-amato Sure no problem. Really appreciate your efforts. Faraday is a great tool that is why I want it to work in every scenario (especially Putty+Xming+Kali). Will report back soon.

**Comment by void-in** [comment] 2015-04-17 07:19
@f-amato The issue is with Xming as well as previous version of Faraday. These are the latest results:
Faraday version checked out from Github in December 2014 + Xming
Result:
As reported in the original issue description.

Faraday version checked out from Github on April 17 2015 with latest supporting files through install.sh script and Xming.
Result:
![faraday_with_xming](https://cloud.githubusercontent.com/assets/1746697/7197472/00d60dc8-e4fb-11e4-87fe-d074d47156f8.JPG)

Faraday version checked out from Github on April 17 2015 with latest supporting files through install.sh  and vcXsrv which is another popular open source X11 server for Windows.
Result
![faraday_with_vcxsrv](https://cloud.githubusercontent.com/assets/1746697/7197562/f0f29718-e4fb-11e4-8cdf-889a102ed0b7.JPG)

So In the end you can close this issue now. Thanks for looking into it. The recommended approach is to get the latest version of Faraday along with vcXsrv (verified) or a different X11 server for Windows other than Xming.

**Comment by f-amato** [comment] 2015-04-30 04:28
Excellent thanks!

**Closed by f-amato** 2015-04-30 04:28 UTC
